name: Genel
description: Yukarıdaki kategorilere uymayan her şey için
title: "[Genel] "
labels:
  - general
body:
  - type: textarea
    id: description
    attributes:
      label: Açıklama
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Ek Bilgi
