name: General
description: For anything that doesn't fit into the other categories
title: "[General] "
labels:
  - general
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional Context / Information
    validations:
      required: false
